# Generated by Django 5.1.4 on 2024-12-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_schedular', '0002_cronjobcontrol_delete_student'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cronjobcontrol',
            index=models.Index(fields=['is_active', 'interval'], name='task_schedu_is_acti_b8f601_idx'),
        ),
    ]
